In [11]:
import pandas as pd
from sklearn.naive_bayes import GaussianNB

df = pd.read_csv ('Assig1-Dataset/train_1.csv', header=None)

# the label is the last column of the dataset
label = df[1024].to_numpy()

# deletes label of EACH ROW (somehow pandas makes magic like this happen) and sends features to array
del df[1024]

# df.to_numpy() is csv in 2d array format
features = [x for x in df.to_numpy()]

# fit model 
model = GaussianNB()
model.fit(features,label)

predicted = model.predict([features[0]])

print(predicted)
# make 32X32 image



0        1
1       14
2        4
3       12
4       20
        ..
1192     6
1193     6
1194     1
1195     1
1196    16
Name: 1024, Length: 1197, dtype: int64
[[ 1  1  1 ...  1  1  1]
 [ 1  1  1 ...  1  1 14]
 [ 1  1  1 ...  1  1  4]
 ...
 [ 1  1  1 ...  1  1  1]
 [ 0  1  1 ...  1  1  1]
 [ 1  1  1 ...  1  1 16]]
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]
 [1 1 1 ... 0 1 1]]
[1]


In [6]:
from math import log2

H = lambda x: -sum([p * log2(p) for p in x])

H([0.99,0.01])

0.08079313589591118